### ISSUE TITLE
Assistance Needed with CDS Engine and Patient Portal Configuration

### ISSUE THREAD

**Issue by swantrace** [asushares/patient#1]
Hi, @preston , I encountered some issues while attempting to run the CDS engine and the patient portal on my laptop and have a few questions regarding the setup and troubleshooting steps.

1. **Patient Repository Configuration:** When I execute `npm run start` in the root directory of the patient repository, the `src/assets/configuration.js` is initialized as follows:

```javascript
(function(window) {
    // Environment variables
    window["PATIENT_PORTAL_DEFAULT_FHIR_URL"] = "";
    window["PATIENT_PORTAL_CONSENT_CDS_ROOT_URL"] = "";
})(this);
```

For using the FHIR server and CDS engine hosted on my local machine, I modified it to:

```javascript
(function (window) {
    // Environment variables
    window["PATIENT_PORTAL_DEFAULT_FHIR_URL"] = "http://localhost:8080/fhir";
    window["PATIENT_PORTAL_CONSENT_CDS_ROOT_URL"] = "http://localhost:3000";
})(this);
```

Is this modification correct?

2. **Environment Variable Substitution:** I’m exploring ways to streamline the process of setting environment variables. Is it possible to use the `envsubst` command to read from a `.env` file? I came across a library named [enbsub](https://www.npmjs.com/package/envsub)—could this be a viable solution?

3. **Variable Naming in Backend Service:** In `src/backend.service.ts` at line 24, the code references `this.cdsUrl = (window as any)["CONSENT_CDS_ROOT_URL"];`. Should the variable `CONSENT_CDS_ROOT_URL` be updated to `PATIENT_PORTAL_CONSENT_CDS_ROOT_URL` for consistency?

4. **Troubleshooting Patient Data Retrieval:** After updating `configuration.js` and launching the patient portal with `ng serve`, I’m unable to retrieve any patient data through the search box. Could this issue be related to the absence of data in my local FHIR server? If so, could you guide me on how to import test data into it?

**Comment by swantrace** [comment]
Hi, @preston 
I extracted the component of form check and added a bootstrap popover to it. Then I found I couldn't push the branch to the patient repository in github. Is it because the patient repository is not in the [developer team](https://github.com/orgs/asushares/teams/developers/repositories)?

Besides that, where I can find the content to show in the popover for each category? This is what I found in a diagram of the paper for substance use, but how can I access to strings for other categories?
```
{
      id: 'categorySubstanceUse',
      label: 'Substance Use',
      contentArr: [
        'Methamphetamine intoxication',
        'Family history-Alcohol abuse',
        'Family history-Drug abuse',
        'Methadone [Presence] in Urine by Screen method',
        'Morphine, lo other',
        'Oplates screen, urine(positive)',
        'Alcohol screening (negative)',
        'History of domestic altercation',
        'Hydrocodone bitartrate 5 mg and paracetamol 325 mg oral tablet',
        'Estazolam 1 mg oral tablet',
      ],
 }
 ```

**Comment by preston** [comment]
@swantrace Looking forward to seeing it! I'm 90% sure it was a permissions thing, yeah.  I'm updated them.. please try again.

The idea for the content of the pop-overs is that the patient portal makes a call to the CDS service to determining which resources should/should not be redacted, and then summarized them visually for the patient to actually see what will/will not be shared given there current Consent configuration. I can help with that today if you need assistance with the CDS integration, as there is some common code I haven't yet extracted to the "core" library.

**Comment by swantrace** [comment]
@preston Thanks, I am not sure which route should be used to get the information, could you please let me know?
